ID_UMAP = "umap"
ID_DROPDOWN = "dropdown"
ID_DROPDOWN_BUTTON = "dropdown-button"
ID_UPLOAD = "upload"
ID_UPLOAD_OUTPUT = "upload-output"
ID_UMAP_DATA = "umap-data"
ID_EXAMPLE_BUTTON = "example-button"